### DISCUSSION TITLE
Assign user role to SSO users

### DISCUSSION THREAD

**Discussion by jimmyzzxhlh** [littleK0i/SnowDDL#103] [Q&A] [answered]
Hi,

My company has SSO configured with Snowflake. How should we manage the user permission in SnowDDL? Obviously we don't really want to store plain passwords as mentioned in the following document. Can we basically just specify the user name and the roles being assigned? 
https://docs.snowddl.com/basic/yaml-configs/user

Thanks for creating SnowDDL! This looks like a much better RBAC management solution for Snowflake than Terraform.

**Comment by littleK0i** [comment, marked as answer]
Currently I have one org which uses SnowDDL on account with activated SSO.

Once you configure SECURITY INTEGRATION, you can simply add new users like this:

```yaml
john_doe:
  login_name: "john_doe@myorg.com"
  first_name: "John"
  last_name: "Doe"
  email: "john_doe@myorg.com"
  business_roles:
    - finance_analyst
    - ml_engineer
```

As far as I know, setting `login_name` for user is enough to make things work.

Terraform is really good for managing infra, but definitely not for objects in Snowflake. At some point I had no choice but to open source SnowDDL, since it was too difficult to manage large accounts.
