### DISCUSSION TITLE
What is the best practice wrt procedures?

### DISCUSSION THREAD

**Discussion by AndreiTapai** [littleK0i/SnowDDL#109] [Q&A]
Hi @littleK0i ,

I have some procedures that are constantly being iterated on. When applying changes to the Snowflake database more often than not we have errors like "Cannot overload procedure test as it would cause ambiguous PROCEDURE overloading." Is it absolutely necessary to run a drop script for these before running snowddl?

**Comment by littleK0i** [comment]
@AndreiTapai , manual drops should not be necessary.

Could you share procedure YAML config (without body) and name of YAML file? I'll try to reproduce it.

Snowflake might have some hidden rules around overloading which are currently not taken into account.

**Reply by AndreiTapai** [reply]
@littleK0i 

sorry for the delay. We made a change as follows:

we had a yaml file `ranking_func(varchar,boolean).yaml` with the following body:

```yaml
arguments:
  string_var: VARCHAR(16777216)
  debug_flag:
    type: BOOLEAN
    default: FALSE

returns: {}
```

this was subsequently changed to:

`ranking_func(varchar).yaml`

```yaml
arguments:
  string_var: VARCHAR(16777216)

returns: {}
```

basically dropping the flag parameter.
