### DISCUSSION TITLE
Support of TABLE RENAME and COLUMN RENAME

### DISCUSSION THREAD

**Discussion by minghungcho** [littleK0i/SnowDDL#17] [Ideas]
Currently, I can handle table & column rename in a pre-deployment script via SnowSQL before the execution of SnowDDL.
However, I am wondering if there is a better way to support rename within SnowDDL YAML config.

What if there is a property such as **former_name** / **aka** that allows you to instruct rename behavior.

I understand this might also create some circular reference problem. But when use carefully, this would reduce the chance of data loss, and eliminate some pre- & post- deployment script needs.

**Proposal**
_public/table/booking.yaml_
```
columns:
  ticket_no:
    type: VARCHAR(13) NOT NULL
    former_name: ticket_number
    comment: "Ticket number"

former_name: bookings
```

Potentially generate the following scripts
```
ALTER TABLE IF EXISTS public.bookings RENAME TO public.booking;
ALTER TABLE IF EXISTS public.booking RENAME COLUMN ticket_number TO ticket_no;

```

OR, generate a better CREATE-SELECT statement during **--apply-replace-table**.
```
CREATE TABLE public.booking
(
ticket_no VARCHAR(13) NOT NULL COMMENT 'Ticket number'
)
AS
SELECT ticket_number::VARCHAR(13) AS ticket_no
FROM public.bookings
```
