### DISCUSSION TITLE
assigning one role to other

### DISCUSSION THREAD

**Discussion by raginc** [littleK0i/SnowDDL#195] [General]
I am trying to create multiple role with one developer role [create schema / alter schema and its objects and few more privileges] and one DBA role, DBA role should have Developer Role + other privileges like create database, backup etc.

DBA role will inherit privs from developer role

how do i assign developer role to dba role using snowDDL. does the developer role should be business role or technical role? and what about DBA role?

can you please give some example of both role

**Comment by littleK0i** [comment]
Normally you do not create DBA roles and roles with "create schema" privilege in SnowDDL, since it defeats the purpose.

Why use object management tool if you want to manage objects manually anyway?

---

For less extreme use cases, you have two options:

**(1) Create two business roles with some overlapping privileges**

E.g.
```yaml
# has limited access to CCC database, only one schema
business_role_1:
  schema_owner:
    - aaa.*
    - bbb.*
    - ccc.ddd
 
# has full access to CCC database, all schemas
business_role_2:
  schema_owner:
    - aaa.*
    - bbb.*
    - ccc.*
```

Assign one business role to each user. This approach is good for clarity.

```yaml
user_1:
  ...
  business_roles:
    - business_role_1

user_2:
  ...
  business_roles:
    - business_role_2
```

**2) Create two business roles with non-overlapping privileges.**

E.g.
```yaml
# has full access to AAA database
business_role_aaa_full:
  schema_owner:
    - aaa.*

# has full access to BBB database
business_role_bbb_full:
  schema_owner:
    - bbb.*

# has full access to CCC database
business_role_ccc_full:
  schema_owner:
    - ccc.*

# has limited access to CCC database
business_role_ccc_limited:
  schema_owner:
    - ccc.ddd
```

Users:
```yaml
user_1:
  ...
  business_roles:
    - business_role_aaa_full
    - business_role_bbb_full
    - business_role_ccc_limited

user_2:
  ...
  business_roles:
    - business_role_aaa_full
    - business_role_bbb_full
    - business_role_ccc_full
```

This approach might be good if you have requirement for very granular permissions and a lot of people are wearing many hats (belong to multiple teams at the same time).

**Reply by raginc** [reply]
Technical role how do I use it for granting all table privileges in specific schema, no grants to other objects


sample_write_role:
  grants:
    DATABASE:USAGE:
      - sample_db
    SCHEMA:USAGE:
      - sample_db.sample_schema
    TABLE:ALL:
      - sample_db.sample_schema.*

is above config correct?

**Reply by littleK0i** [reply]
Under normal circumstances, you should barely need any tech roles outside of some very specific use cases.

For "write" permissions you're probably looking for `schema_owner` parameter in business role: https://www.expatforum.com/forums/spain-expat-forum-for-expats-living-in-spain.2/

```yaml
sample_writer_role:
  schema_owner:
    - sample_db.sample_schema
```

Under the hood it grants schema role with "CREATE TABLE" and ownership on all future tables. OWNERSHIP includes all other grants. Very easy.

---

With technical roles, it will mostly work as well, except `ALL` privilege. All privileges should be listed explicitly. It should look like this:

```
TABLE:SELECT,UPDATE,DELETE,TRUNCATE:
  - sample_db.sample_schema.*
```
