### DISCUSSION TITLE
User passwords getting reset after every SnowDDL Run

### DISCUSSION THREAD

**Discussion by bhargavpatil-dignifi** [littleK0i/SnowDDL#202] [Q&A]
Recently, we added user types to user.yaml file.

Since then there is an alter statement that is unsetting the passwords. 
We are not able to understand from the documentation as to what is causing these password resets.

**SnowDDL CLI Command deploying SnowDDL:**
`snowddl --env-prefix dev --placeholder-values="{\"env\":\"dev\", \"aws_account_id\":\"***\"}" --apply-unsafe apply`

**Sample type=person user:**
```
bhargavpatil:
  login_name: bhargav.patil
  display_name: "Bhargav Patil"
  first_name: Bhargav
  last_name: Patil
  disabled: False
  email: bhargav.patil@test.com
  type: "PERSON"
  business_roles:
    - engineer
  default_namespace: test
  default_warehouse: test_wh
```
