### DISCUSSION TITLE
Outbound share:  table select grant & alter share error

### DISCUSSION THREAD

**Discussion by bhargavpatil-dignifi** [littleK0i/SnowDDL#215] [Q&A]
I am creating an outbound share to a reader account of the same type (standard->standard)
In the environment, Database & schema is managed by SnowDDL whereas tables are managed/created using DBT

Below is the snippet of my outbound-share.yaml file:
```
test_share:
  accounts:
    - test_org.test_reader
  grants:
    DATABASE:USAGE:
      - test_db
    SCHEMA:USAGE:
      - test_db.test_schema
    TABLE:SELECT:
      - test_db.test_schema.*
  
  comment: test share created using snowddl
```

In Outbound share.yaml, I am facing 2 issues:

1. "TABLE:SELECT: " is not able to detect the tables in the schema.
Error: it either doesn't run any "grant select to share" or says no table match the wildcard provided in yaml file.

I suspect the issue is because they are not defined in the snowddl config & when i tried to create a test table using snowddl, it run the grant select to the share for that table.
What can be done to solve this in out current setup i.e. dbt creating the tables & not defining it in the snowddl config & have grant select to share run successfully?

2. I am setting the account in the outbound-share.yaml & when snowddl wants to set this using alter share, it is failing, below is the error message: 
```
WARNING - Resolved SHARE [TEST_SHARE]: ERROR
(
    message   =>  SQL compilation error:
invalid property 'SHARE_RESTRICTIONS' for 'SHARE'
    errno     =>  1420
    sqlstate  =>  22023
    sfqid     =>  01bc1b43-0205-20cd-0013-********
    sql       =>  ALTER SHARE "TEST_SHARE" SET ACCOUNTS = "TEST_ORG"."TEST_READER"
SHARE_RESTRICTIONS = FALSE
```
Due to this, my share is getting created but failing to set the "TO" attribute as seen in "SHOW SHARES" command.
