### DISCUSSION TITLE
Key-pair authentication support

### DISCUSSION THREAD

**Discussion by jimmyzzxhlh** [littleK0i/SnowDDL#225] [General]
Does SnowDDL support key pair authentication in Snowflake?
Context: https://docs.snowflake.com/en/user-guide/key-pair-auth
I know SnowDDL can support password encryption here: https://docs.snowddl.com/guides/other-guides/encrypt-user-passwords#usage-notes

**Comment by littleK0i** [comment]
Yes, of course. Use the following CLI parameters:

```
  -k PRIVATE_KEY                   Path to private key file (default: SNOWFLAKE_PRIVATE_KEY_PATH env variable)
  ...
  --passphrase PASSPHRASE          Passphrase for private key file (default: SNOWFLAKE_PRIVATE_KEY_PASSPHRASE env variable)
```

You may also use environment variable `SNOWFLAKE_PRIVATE_KEY` to pass the key as string. It is quite useful for CI/CD.

**Reply by jimmyzzxhlh** [reply]
Thanks! How would the yaml config look like in this case? For username/password there is something like the following:

```
john_doe:
  first_name: John
  last_name: Doe
  password: !decrypt gAAAAABmlTl8AHfqJXFfDI4jqOGiaBLZ2dDMbMCqkNyOH_EzcRYGmFxSr_fvx8mgGBWD7sOYYIFCp5AqvG8k5kGM5R5ssYZgwA
```

**Reply by littleK0i** [reply]
Ah, this..

```
john_doe:
  first_name: John
  last_name: Doe
  rsa_public_key: !decrypt gAAAAABmlTl8AHfqJXFfDI4jqOGiaBLZ2dDMbMCqkNyOH_EzcRYGmFxSr_fvx8mgGBWD7sOYYIFCp5AqvG8k5kGM5R5ssYZgwA
```
