### DISCUSSION TITLE
Tech Role Inheritance

### DISCUSSION THREAD

**Discussion by jbdignifi** [littleK0i/SnowDDL#35] [Q&A]
Can a tech role assume/inherit another tech role?

In the simplest case, we have a tech role that inserts new rows into a "refresh" table, but we want this privilege inherited by many upstream tech roles.

I have looked through the source and believe this is not supported at the moment, but please correct me if this is not the case. It is curious that business roles can inherit tech roles. We could use business roles as a workaround, but we prefer the control and granularity afforded by tech roles, it helps permissions fit processes more tightly.

I understand this may be a niche use-case, and this is a difficult feature to join with the existing hierarchy system (due to potential conflicts and circular dependencies that must be checked). Either way, I think it is a worthwhile consideration to prevent repetition, without this feature the same permissions must be copied to each tech role.

**Comment by littleK0i** [comment]
In theory, you should be able to solve this problem without any additional features.

Tech roles are never used on their own. Tech roles are assigned to business roles, and business roles are assigned to specific user roles. Only user roles are actually assigned to end users, but not any other type.

You may try something like this:

1) Define one tech role with privileges for "refresh" table.
2) Assign this tech role to as many business roles as necessary.
3) Assign business roles to specific users.

---

Specific example:

**tech_role.yaml**
```yaml
refresh_table_rw:
  grants:
    DATABASE:USAGE:
      - my_db
    SCHEMA:USAGE:
      - my_db.my_schema
    TABLE:SELECT,INSERT,UPDATE,DELETE:
      - my_db.my_schema.refresh_table
```

**business_role.yaml**
```yaml
etl_script:
  ...
  tech_roles:
    - refresh_table_rw

another_script:
  ...
  tech_roles:
    - refresh_table_rw

business_analyst:
  ...
  tech_roles:
    - refresh_table_rw

data_developer:
  ...
  tech_roles:
    - refresh_table_rw
```

**user.yaml**
```yaml
my_etl_script_user:
  ...
  business_roles:
    - etl_script

another_script_user:
  ...
  business_roles:
    - another_script

john_doe:
  ...
  business_roles:
    - business_analyst

jane_smith:
  ...
  business_roles:
    - data_developer
 ```
