### ISSUE TITLE
Incorrect Sequence reference in table

### ISSUE THREAD

**Issue by minghungcho** [littleK0i/SnowDDL#10]
Here is my test setup.
```
sample_db / db / public
sequence /
  seq_emp_id.yaml
table
  employee.yaml
```

**I purposely name the folder under configure folder, sample_db, as db**
Here is the scenario, db will be deployed to different target_db based on environment. ex. _dev, _qa, ..
So I expect the column with default_sequence to reference the sequence object created in the its own database (same as target_db).

```
seq_emp_id.yaml
start: 1
interval: 1

employee.yaml
columns:
  employee_id:
    type: number(10,0)
    default_sequence: seq_emp_id
  name: varchar(16777216)
```

Using SingleDB mode with **`-c sample_db --config-db db --target-db sample_db`**

The Sequence object, seq_emp_id, was created correctly.
```
CREATE SEQUENCE "SAMPLE_DB"."PUBLIC"."SEQ_EMP_ID"
START = 1
INCREMENT = 1;
```
However, table creation failed with incorrect sequence reference.
```
2022-06-30 22:51:19.506 - WARNING - Resolved TABLE [SAMPLE_DB.PUBLIC.EMPLOYEE]: ERROR
(
    message   =>  SQL compilation error: error line 3 at position 41
invalid identifier 'DB.PUBLIC.SEQ_EMP_ID.NEXTVAL'
    errno     =>  904
    sqlstate  =>  42000
    sfqid     =>  01a54e6b-0c03-3e1a-0002-5fae00021032
    sql       =>  CREATE TABLE "SAMPLE_DB"."PUBLIC"."EMPLOYEE"
(
      "EMPLOYEE_ID" NUMBER(10,0) DEFAULT DB.PUBLIC.SEQ_EMP_ID.NEXTVAL
    , "NAME" VARCHAR(16777216)
)
)
```
It will make more sense if DEFAULT is set to SAMPLE_DB.PUBLIC.SEQ_EMP_ID.NEXTVAL, which is target_db.
