### ISSUE TITLE
Pipe resolver adds quotes in include_metadata elements

### ISSUE THREAD

**Issue by leopasta-enable** [littleK0i/SnowDDL#111]
**Describe the bug**
With a pipe yaml similar to:
```yaml
copy:
  table: monthly_cost_usage
  stage: monthly_cost_usage
  pattern: '.*[.]csv'
  options:
    match_by_column_name: case_insensitive
    include_metadata:  
      - lake__file_name = METADATA$FILENAME
      - lake__file_row_number = METADATA$FILE_ROW_NUMBER
      - lake__file_content_key = METADATA$FILE_CONTENT_KEY
      - lake__file_last_modified = METADATA$FILE_LAST_MODIFIED
      - lake__start_scan_time = METADATA$START_SCAN_TIME
auto_ingest: ${{auto_ingest_azure_spend}}
integration: notification_integration
```
Snowddl produces a CREATE PIPE were each of the metadata expressions are enclosed in quotes, which is not accepted by snowflake syntax.

**Expected behavior**
This is the produced DDL:
```sql
CREATE OR REPLACE PIPE "DEVOPS"."INGESTION"."MONTHLY_COST_USAGE" 
AUTO_INGEST = FALSE
AS
COPY INTO "DEVOPS"."INGESTION"."MONTHLY_COST_USAGE"
FROM @"DEVOPS"."INGESTION"."MONTHLY_COST_USAGE"
PATTERN = '.*[.]csv'
MATCH_BY_COLUMN_NAME = 'case_insensitive'
INCLUDE_METADATA = ('lake__file_name = METADATA$FILENAME', 'lake__file_row_number = METADATA$FILE_ROW_NUMBER', 'lake__file_content_key = METADATA$FILE_CONTENT_KEY', 'lake__file_last_modified = METADATA$FILE_LAST_MODIFIED', 'lake__start_scan_time = METADATA$START_SCAN_TIME');

COMMENT ON PIPE "DEVOPS"."INGESTION"."MONTHLY_COST_USAGE" IS '#w3X5avtIL68UgzcD';
```
Which snowflake errors:
```
2024-07-05 19:48:17.688 - WARNING - Resolved PIPE [DEVOPS.INGESTION.MONTHLY_COST_USAGE]: ERROR
(
    message   =>  SQL compilation error:
invalid value 'TOK_CONSTANT_LIST' for property 'INCLUDE_METADATA'
    errno     =>  1422
    sqlstate  =>  22023
    sfqid     =>  01b57888-0000-530b-0000-999d008f0bf6
    sql       =>  CREATE OR REPLACE PIPE "DEVOPS"."INGESTION"."MONTHLY_COST_USAGE" 
AUTO_INGEST = FALSE
AS
COPY INTO "DEVOPS"."INGESTION"."MONTHLY_COST_USAGE"
FROM @"DEVOPS"."INGESTION"."MONTHLY_COST_USAGE"
PATTERN = '.*[.]csv'
MATCH_BY_COLUMN_NAME = 'case_insensitive'
INCLUDE_METADATA = ('lake__file_name = METADATA$FILENAME,', 'lake__file_row_number = METADATA$FILE_ROW_NUMBER,', 'lake__file_content_key = METADATA$FILE_CONTENT_KEY,', 'lake__file_last_modified = METADATA$FILE_LAST_MODIFIED,', 'lake__start_scan_time = METADATA$START_SCAN_TIME')
)
```

**Attach log**
Included in the "expected behaviour" section

**Attach YAML config (if applicable)**
Included in the "describe the bug" section

**Comment by littleK0i** [comment]
Hmm, looks like a new feature. I'll take a look.

Did you consider using `transform` parameter and specifing all columns explicitly? Initially it's a bit more work compared to "MATCH_BY_COLUMN_NAME". But it will be much easier to add custom transformations when you need it. Rounding a number, trimming a string, converting timestamp, etc.

And it should work with any SQL expressions out of the box, including metadata columns.

**Comment by leopasta-enable** [comment]
Thanks, yes I consider that a possible workaround. I confirmed that if I edit the quotes out and apply manually, snowddl won't detect it as a difference in plans later on, so that might be a viable alternative as well.

Long term, what do you think of handling this special case in https://github.com/littleK0i/SnowDDL/blob/549fcc875f2111bd2b138262ca087e6c75cb0a99/snowddl/resolver/pipe.py#L218 ?

**Comment by littleK0i** [comment]
@leopasta-enable , please try version `0.29.1`.

Now it is possible to set `match_by_column_name` and `include_metadata` as dedicated parameters with special logic, similar to `file_format`. For example:

```yaml
copy:
  table: pi003_tb1
  stage: pi003_st1
  file_format: pi003_ff1

  match_by_column_name: case_sensitive

  include_metadata:
    metadata_file_name: METADATA$FILENAME
    metadata_file_row_number: METADATA$FILE_ROW_NUMBER
    metadata_file_content_key: METADATA$FILE_CONTENT_KEY
    metadata_file_last_modified: METADATA$FILE_LAST_MODIFIED
    metadata_file_start_scan_time: METADATA$START_SCAN_TIME

auto_ingest: false
```

Documentation was updated as well: https://docs.snowddl.com/basic/yaml-configs/pipe
