### ISSUE TITLE
Permission issues when creating dynamic tables

### ISSUE THREAD

**Issue by Github-dm-CDE** [littleK0i/SnowDDL#125]
**Describe the bug**
When creating dynamic tables, these are created with the `MY_DB__MY_SCHEMA__OWNER__S_ROLE` owner. Attempts to update the dynamic tables then fail, as they cannot see either the warehouse to be used or the base table to be used from another schema. Both the warehouse to be used and the schema to be used were created with the `SNOWDDL_ADMIN` as owner.
As soon as the `MY_DB__MY_SCHEMA__OWNER__S_ROLE` is manually assigned the right to use the warehouse, for example, it can be seen and used by the dynamic table.
Unfortunately, it is not entirely clear to us from the documentation how we can avoid this manual intervention and automate the whole thing.

**Expected behavior**
SnowDDL should automatically take care of the necessary permissions for the objects required to update dynamic tables.

**Attach log**
![Screenshot 2024-09-24 100543](https://github.com/user-attachments/assets/4c873855-186a-4dd4-ac90-8b6e92e0f20f)

**Attach YAML config (if applicable)**
PROD/LANDING/table/DIM_PAGE.yaml
```yaml
columns:
  SOME_COLUMN:
    type: VARCHAR(2)
cluster_by:
  - SOME_COLUMN
```

PROD/MSTR/dynamic_table/DIM_PAGE_DY_V20240822.yaml
```yaml
columns:
  SOME_COLUMN: ''
text: |-
  SELECT
    SOME_COLUMN
  FROM LANDING.DIM_PAGE
  QUALIFY (LEAD(SOME_COLUMN) OVER ()) IS NULL
cluster_by:
  - SOME_COLUMN
target_lag: 1 hour
warehouse: XLARGE
initialize: ON_SCHEDULE
```
