### ISSUE TITLE
Permissions issues when creating dynamic table that selects across databases

### ISSUE THREAD

**Issue by apd-bbaker** [littleK0i/SnowDDL#134]
**Describe the bug**
administrator__b_role has ownership of both db_a__owner_d_role and db_b__owner_d_role. The role permissions do not seem to bubble up to the b_role level when it comes to dynamic tables.

When creating a dynamic table in db_a that selects from a table in db_b, an error is thrown that there's insufficient access to the database to create the dynamic table. After some testing, it seems that the db_a__owner__d_role doesn't have necessary permissions to access objects owned by db_a__owner__d_role.

After granting the access manually, the next error that occurs is on the warehouse with a similar permissions issue. Manually granting access does finally allow the dynamic table to be created. 

**Expected behavior**
SnowDDL automatically grants necessary access to necessary objects for dynamic tables' unique permission structure of ownership and warehouse dependency. This may be (probably) an additional config item that I overlooked.

**Attach log**
N/A

**Attach YAML config (if applicable)**
N/A

**Comment by littleK0i** [comment]
Dynamic tables are running with object owner privileges. It is how Snowflake designed it.

Take a look at large block of `owner_*` grant parameters in SCHEMA config: https://docs.snowddl.com/basic/yaml-configs/schema

- **owner_schema_read** - list schemas which should be available to "owner" role of this schema;
- **owner_warehouse_usage** - list warehouses which should available to "owner" role of this schema;

We considered automated grants at some point, but decided against it. Currently it is not possible to reliably parse SQL and identify all dependent objects. Also, it is possible to query dynamically named objects via FUNCTION or PROCEDURE.

**Comment by apd-bbaker** [comment]
@littleK0i We're using database owner permissions model rather than schema due to the use of some replication platforms and dbt that need to be able to create and drop their own schemas. I believe database level is the correct way to approach this, but let me know if I've misunderstood the intent behind that permission model.

The custom permission model we have in place that has been working well with Fivetran + dbt is below. Since we're following a medallion data lakehouse architecture with bronze/silver/gold, we need the database owners of higher layers to be able to have full read access to the layers below it to transform the data using dynamic tables.

What I think I need is a `owner_database_read` option on the `database` config that allows me to grant additional permission to the lower databases as the database owner of a higher layer. I tried doing this with `owner_global_roles`, but since that's assumed to be unmanaged by SnowDDL it doesn't allow me to parameterize the database names with `${env_prefix}`.

Thoughts on how to go about this?

```yaml
custom_permission_model:
  ruleset: database_owner

  owner_create_grants:
    - alert
    - dynamic_table
    - event_table
    - external_table
    - file_format
    - function
    - materialized_view
    - pipe
    - procedure
    - sequence
    - stage
    - stream
    - table
    - task
    - view

  owner_future_grants:
    alert: [ownership]
    dynamic_table: [ownership]
    event_table: [ownership]
    external_table: [ownership]
    file_format: [ownership]
    function: [ownership]
    materialized_view: [ownership]
    pipe: [ownership]
    procedure: [ownership]
    sequence: [ownership]
    stage: [ownership]
    stream: [ownership]
    table: [ownership]
    task: [ownership]
    view: [ownership]

  read_future_grants:
    dynamic_table: [select]
    external_table: [select, references]
    file_format: [usage]
    function: [usage]
    materialized_view: [select, references]
    procedure: [usage]
    sequence: [usage]
    stage: [read, usage]
    stream: [select]
    table: [select, references]
    view: [select, references]

```
