### ISSUE TITLE
Unexpected SHARE_RESTRICTIONS Parameter in ALTER SHARE SET Causes SQL Compilation Error

### ISSUE THREAD

**Issue by DoMy91** [littleK0i/SnowDDL#181]
**Describe the bug**
If we try to create a new share in SnowDDL while specifying some consumer accounts, the `ALTER SHARE SET` command is executed after the share is created to add the accounts. However, the `SHARE_RESTRICTIONS=FALSE` parameter is added by default, even if it is not specified in the share configuration. The issue is that this parameter can be used with `ALTER SHARE ADD`, but not with `ALTER SHARE SET`: [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/alter-share#parameters).

**Expected behavior**
If `SHARE_RESTRICTIONS` is missing from the configuration, it should not be added automatically to `ALTER SHARE ADD`.

**Attach log**
```
2025-02-11 11:56:48.632 - WARNING - Resolved SHARE [X_SHARE]: ERROR
(
   message   =>  SQL compilation error:
invalid property 'SHARE_RESTRICTIONS' for 'SHARE'
    errno     =>  1420
    sqlstate  =>  22023
    sfqid     =>  01ba520c-0305-e2b5-0001-3e92127e8d1e
    sql       =>  ALTER SHARE "X_SHARE" SET ACCOUNTS = "ORG"."DOMAIN"
SHARE_RESTRICTIONS = FALSE
)
```

**Attach YAML config (if applicable)**
```
X_SHARE:
  accounts:
    - ORG.DOMAIN
  grants:
    DATABASE:USAGE:
      - my_db
    SCHEMA:USAGE:
      - my_db.my_schema
    VIEW:SELECT:
      - my_db.my_schema.*
```
