### ISSUE TITLE
Add support for pre-defined AWS_SNS_TOPIC on external AWS S3 stages

### ISSUE THREAD

**Issue by apd-bbaker** [littleK0i/SnowDDL#183]
## Is your feature request related to a problem? Please describe.
When adding the `directory` > `aws_sns_topic` element for an external S3 stage's directory table config, an error is thrown that it's an unknown property.

## Describe the solution you'd like
SnowDDL is able to generate the create or alter statement for an external s3 stage that includes the `aws_sns_topic` property if it has been pre-configured in AWS and should be subscribed to by Snowflake's SQS.

## Describe alternatives you've considered
Manually executing stage creation code.

### Error Detail
```
File "/usr/local/lib/python3.12/site-packages/snowddl/resolver/stage.py", line 185, in _compare_directory
    raise ValueError(f"Unknown DIRECTORY property [{prop_name}] for stage [{bp.full_name}]")
ValueError: Unknown DIRECTORY property [AWS_SNS_TOPIC] for stage [RAW_LAYER.S3.EXTERNAL_S3_STAGE]
```

### Workaround SQL executed on Snowflake
```sql
create or replace stage raw_layer.s3.external_s3_stage
    url = 's3://org-solution-external-stage'
    storage_integration = external_s3
    directory = (
        enable = true
        auto_refresh = true
        aws_sns_topic = 'arn:aws:sns:us-east-1:000000000000:org-solution-external-stage'
);
```

### Desired yaml config ability
```yaml
# database > schema > stage > external_s3_stage.yaml
url: "s3://org-solution-external-stage"
storage_integration: "external_s3"
directory:
  enable: true
  refresh_on_create: true
  auto_refresh: true
  aws_sns_topic: "arn:aws:sns:us-east-1:000000000000:org-solution-external-stage"
```
