### ISSUE TITLE
Stage encryption type is case sensitive

### ISSUE THREAD

**Issue by kokorin** [littleK0i/SnowDDL#197]
**Describe the bug**
We occasionally configured a stage with lowercase encryption type:

```yaml
directory:
  enable: true
encryption:
  type: snowflake_sse
```

The stage was created by apply, but on the next plan SnowDDL suggests stage re-creation:

```
--- Suggested DDL ---
CREATE OR REPLACE STAGE "<DB>"."<Schema>"."<Stage>"
DIRECTORY = ( ENABLE = TRUE )
ENCRYPTION = ( TYPE = 'snowflake_sse' );
```

With uppercase type in YAML plan suggests no re-creation of the stage:

```yaml
directory:
  enable: true
encryption:
  type: SNOWFLAKE_SSE
```

**Expected behavior**
I can think of 2 options:
1. StageResolver to convert encryption type to uppercase
2. StageParser to set encryption type to be enum of SNOWFLAKE_SSE and SNOWFLAKE_FULL
