### ISSUE TITLE
Permission Model: Owner Future Grants on Database Role

### ISSUE THREAD

**Issue by kokorin** [littleK0i/SnowDDL#218]
**Describe the bug**

We want to grant Database Owner Role ownership on Database Roles (created manually).

```yaml
database_owner:
  inherit_from: <another model>
  ruleset: DATABASE_OWNER
  owner_future_grants:
    DATABASE_ROLE: [OWNERSHIP]
```

SnowDDL suggests granting ownership not only on DB Roles in DB, but also on DB Roles in known Schemas (which should not work):

```sql
GRANT OWNERSHIP ON FUTURE DATABASE ROLES IN DATABASE "<DB>" TO ROLE "<DB>__OWNER__D_ROLE";

GRANT OWNERSHIP ON ALL DATABASE ROLES IN DATABASE "<DB>" TO ROLE "<DB>__OWNER__D_ROLE" COPY CURRENT GRANTS;

-- statements below lead to an error
GRANT OWNERSHIP ON FUTURE DATABASE ROLES IN SCHEMA "<DB>"."<Schema>" TO ROLE "<DB>__OWNER__D_ROLE";

GRANT OWNERSHIP ON ALL DATABASE ROLES IN SCHEMA "<DB>"."<Schema>" TO ROLE "<DB>__OWNER__D_ROLE" COPY CURRENT GRANTS;
```

**Expected behavior**
Ownership is granted on DB Roles in DB. No ownership is granted on DB Roles in Schemas.
