### ISSUE TITLE
Newly created warehouses have resource_constraint in Snowflake, SnowDDL wants to set them back to null

### ISSUE THREAD

**Issue by jfiore-pg** [littleK0i/SnowDDL#220]
**Describe the bug**
Standard Virtual Warehouses now have a `resource_constraint` property that gets set when you create a new Warehouse.
https://docs.snowflake.com/en/sql-reference/sql/create-warehouse#:~:text=support%20on%20ARM).-,RESOURCE_CONSTRAINT,-%3D%20%7B%20STANDARD_GEN_1
By default at present, that gets set to `STANDARD_GEN_1`
I think previously, `resource_constraint` only applied to Snowpark-optimized warehouses.
The result is that now every run of SnowDDL now wants to alter the Warehouse's `resource_constraint` to `null` on warehouses that were created relatively recently.

This behavior occurs both on version `0.48.1` (the original version I was using) and the latest version: `0.51.0`

**Expected behavior**
When there are no changes to the Warehouse configuration, it shouldn't output any alter statements.

**Attach log**
Log using version `0.51.0`
```
2025-05-20 09:34:53.891 - INFO - Snowflake version = 9.13.2 (ENTERPRISE), SnowDDL version = 0.51.0
2025-05-20 09:34:53.891 - INFO - Account = <redacted>, Region = AWS_EU_CENTRAL_1
2025-05-20 09:34:53.891 - INFO - Session = <redacted>, User = <redacted>
2025-05-20 09:34:53.891 - INFO - Role = SNOWDDL_ADMIN, Warehouse = DEFAULT_WH
2025-05-20 09:34:53.891 - INFO - Roles in session = SYSADMIN,SECURITYADMIN
2025-05-20 09:34:53.891 - INFO - ---
2025-05-20 09:34:54.975 - INFO - Resolved WAREHOUSE [TABLEAU_WH]: ALTER
2025-05-20 09:35:21.690 - INFO - Executed 0 DDL queries, Suggested 1 DDL queries
--- Suggested DDL ---

ALTER WAREHOUSE "TABLEAU_WH" SET
RESOURCE_CONSTRAINT = NULL;
```

**Attach YAML config (if applicable)**
Original Warehouse configuration:
```
tableau_wh:
  size: SMALL
  auto_suspend: 60
  min_cluster_count: 1
  max_cluster_count: 3
  comment: "Warehouse for Tableau Workloads"
```
If you run this now and create a new warehouse, you will see if you run `SHOW WAREHOUSES` that the `resource_constraint` column is set to `STANDARD_GEN_1` instead of `null`.

As a result, every time I run a `plan` or `apply`, SnowDDL outputs:
```
ALTER WAREHOUSE "TABLEAU_WH" SET
RESOURCE_CONSTRAINT = NULL;
```

I attempted to modify the YAML configuration to:
```
tableau_wh:
  size: SMALL
  auto_suspend: 60
  min_cluster_count: 1
  max_cluster_count: 3
  comment: "Warehouse for Tableau Workloads"
  resource_constraint: STANDARD_GEN_1
```

But this has no effect because the `warehouse` parser only looks at the `resource_constraint` if the `type` == `SNOWPARK-OPTIMIZED`

`snowddl/parser/warehouse.py`
```
if warehouse_type == "SNOWPARK-OPTIMIZED":
            resource_constraint = warehouse_params.get("resource_constraint", "MEMORY_16X")
```
