### ISSUE TITLE
Outbound Shares do not always have to have Accounts specified

### ISSUE THREAD

**Issue by richard-cybersyn** [littleK0i/SnowDDL#44]
**Describe the bug**
Currently for outbound shares there is only one possible resolution with `accounts` being empty, and that's to explicitly, set `ACCOUNTS` to `null`.

https://github.com/littleK0i/SnowDDL/blob/4aceb277fbf88738890793c8254f8126f861f80c/snowddl/resolver/outbound_share.py#L113-L117

**Expected behavior**
There is definitely a need to create shares without any accounts associated with it at creation time, and no `ALTER` should be run when `accounts` are not specified. Snowflake Marketplace operates with outbound `shares` and shared accounts are not specified up front. If you specify an `outbound_share.yaml` `share` without `accounts` filled in, no `ALTER` ddl should run.

**Attach log**
N/A

**Attach YAML config (if applicable)**
```yaml
test_share_1:
  grants:
    DATABASE:USAGE:
      - test_db
    SCHEMA:USAGE:
      - test_db.test_schema
    VIEW:SELECT:
      - test_db.test_schema.*
```
