### ISSUE TITLE
Unable to set TABLE() return type

### ISSUE THREAD

**Issue by AndreiTapai** [littleK0i/SnowDDL#99]
**Describe the bug**
When declaring a procedure I would like to be able to set the return type to `TABLE()` since I do not know the return schema before the procedure executes.  Currently I get an error.

**Expected behavior**
Compiles appropriately. 

See Snowflake docs: https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-snowflake-scripting

**Attach log**
`ValueError: Could not parse data type string [TABLE()]`

**Attach YAML config (if applicable)**
```yaml
arguments:
  my_arg: VARCHAR(16777216)

returns: TABLE()

body: !include sql/my_sql.sql
```

Any help would be appreciated!
